image: elizabethdev/gitpod:tabby-aws

jetbrains:
  intellij:
    prebuilds:
      version: both
    plugins:
      - com.github.copilot
      - jetbrains.plugins.jade

tasks:
  - init: yarn install
    command: yarn run dev
